STOCK_MARKET_OPEN_TIME = "06:00"
STOCK_MARKET_CLOSE_TIME = "12:55"
MAX_STOP_LOSS_PERCENT = 0.07
STOCK_SCANNER_PARTITION_COUNT = 20
STOCKS_TO_CHECK = ["AAPL", "INTC", "AMD", "NVDA", "TSLA", "FB", "MSFT", "AVGO", "QCOM", "AMZN", "GOOG", "IBM", "TWTR", "NFLX", "TWLO", "ETSY", "ROKU", "ZIOP"] 
ARTICLE_MIN_COUNT_NEWS = 10 # needs ARTICLE_MIN_COUNT_NEWS articles or more to buy stocks based on news classifier
