STOCK_MARKET_OPEN_TIME = "06:00"
STOCK_MARKET_CLOSE_TIME = "12:55"
MAX_STOP_LOSS_PERCENT = 0.06
STOCK_SCANNER_PARTITION_COUNT = 20
STOCKS_TO_CHECK = ["AAPL", "INTC", "AMD", "NVDA", "TSLA", "FB", "MSFT", "AVGO", "CAVA","AMZN","RKT","SNAP","SPNY","VEA","BRK.B","IBM","JPM","META","MSFT","NTB","NVDA","PLTR","PPA","RIVN","SPY","TBT","UBER","WMT","AXP","TEVA","GOOGL","RL","SPXL","V","CLSK","IDEX","XLE","EQT","MSTR","GLXY","IOO","PLA","FNGU","PBW","FWRG","BICE","SMG","CRON","MNSO","GGSY","BOSSY","DMB","PSO","ARCO","ADT","GEBHY","AAL","BAC","BRK.A","DIA","BKNG","QCOM", "AMZN", "GOOG", "IBM", "TWTR", "NFLX", "TWLO", "ETSY", "ROKU", "ZIOP"]
ARTICLE_MIN_COUNT_NEWS = 7 # needs ARTICLE_MIN_COUNT_NEWS articles or more to buy stocks based on news classifier




