name: strat_backtester_env
channels:
  - conda-forge
  - defaults
dependencies:
  - brotli
  - brotli-bin
  - bzip2
  - ca-certificates
  - certifi
  - contourpy
  - cycler
  - fonttools
  - freetype
  - gettext
  - gettext-tools
  - glib
  - glib-tools
  - gst-plugins-base
  - gstreamer
  - icu
  - intel-openmp
  - kiwisolver
  - krb5
  - lcms2
  - lerc
  - libasprintf
  - libasprintf-devel
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang13
  - libdeflate
  - libexpat
  - libffi
  - libgettextpo
  - libgettextpo-devel
  - libglib
  - libhwloc
  - libiconv
  - libintl
  - libintl-devel
  - libjpeg-turbo
  - liblapack
  - libogg
  - libpng
  - libsqlite
  - libtiff
  - libvorbis
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gmp
  - m2w64-libwinpthread-git
  - matplotlib
  - matplotlib-base
  - mkl
  - msys2-conda-epoch
  - munkres
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pcre2
  - pillow
  - pip
  - ply
  - pthread-stubs
  - pthreads-win32
  - pyparsing
  - pyqt
  - pyqt5-sip
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - qt-main
  - setuptools
  - sip
  - six
  - tbb
  - tk
  - toml
  - tomli
  - tornado
  - tzdata
  - ucrt
  - vc
  - vc14_runtime
  - vs2015_runtime
  - wheel
  - xorg-libxau
  - xorg-libxdmcp
  - zstd
  - pip:
      - appdirs
      - beautifulsoup4
      - bs4
      - charset-normalizer
      - colorama
      - cssselect
      - et-xmlfile
      - fake-useragent
      - feedparser
      - idna
      - importlib-metadata
      - lxml
      - openpyxl
      - parse
      - pyee
      - pyppeteer
      - pyquery
      - requests
      - requests-html
      - sgmllib3k
      - soupsieve
      - tqdm
      - typing-extensions
      - urllib3
      - w3lib
      - websockets
      - yahoo-fin
      - zipp